#!/usr/bin/env node

/**
 * Auto-generate index.md from memory bank files
 * Updates file summaries and last updated dates
 */

const fs = require('fs');
const path = require('path');

const MEMORY_BANK_PATH = path.join(__dirname, '../../memory-bank');

const FILE_METADATA = {
  'project-brief.md': {
    purpose: 'Phạm vi + mục tiêu cốt lõi',
    sections: 'Objective, Core Features, Non-Goals, Success Metrics',
    frequency: 'Hiếm (khi pivot)'
  },
  'product-context.md': {
    purpose: 'Vấn đề, user goals, UX định hướng',
    sections: 'Problem, Target Users, User Stories, Experience Notes',
    frequency: 'Khi business thay đổi'
  },
  'system-patterns.md': {
    purpose: 'Kiến trúc, pattern, layer, flow',
    sections: 'Layer Diagram, Data Flow, Key Patterns, Integration Points',
    frequency: 'Khi pattern mới ổn định'
  },
  'tech-context.md': {
    purpose: 'Stack, constraints, deps, env',
    sections: 'Stack Table, Version Requirements, Env Setup, External Services',
    frequency: 'Khi thêm/loại công nghệ'
  },
  'active-context.md': {
    purpose: 'Công việc hiện tại, sessions, next steps',
    sections: 'Current Focus, Recent Sessions, Next Steps, Open Questions',
    frequency: 'Mỗi phiên'
  },
  'progress.md': {
    purpose: 'Tiến độ: Done / In progress / Blocked / Risks',
    sections: 'Task Status Table, Weekly Plans, Risks',
    frequency: '1–3 ngày'
  },
  'decisions/recent.md': {
    purpose: 'Quyết định mới (ngắn)',
    sections: 'Reverse chronological decisions with status',
    frequency: 'Khi phát sinh'
  },
  'glossary.md': {
    purpose: 'Thuật ngữ domain',
    sections: 'Domain terminology definitions',
    frequency: 'Khi domain mở rộng'
  }
};

class IndexUpdater {
  constructor() {
    this.currentDate = new Date().toISOString().split('T')[0];
  }

  // Get file last modified date
  getFileLastModified(filePath) {
    try {
      const stats = fs.statSync(filePath);
      return stats.mtime.toISOString().split('T')[0];
    } catch (error) {
      return 'Unknown';
    }
  }

  // Read first few lines of file to extract title/summary
  getFileSummary(filePath) {
    try {
      const content = fs.readFileSync(filePath, 'utf8');
      const lines = content.split('\n').slice(0, 5);

      // Extract title (first # line)
      const titleMatch = content.match(/^#\s+(.+)$/m);
      const title = titleMatch ? titleMatch[1] : 'No title found';

      // Extract brief description (first paragraph)
      const description = lines.find(line => line.trim() && !line.startsWith('#')) || '';

      return {
        title: title.substring(0, 50) + (title.length > 50 ? '...' : ''),
        description: description.substring(0, 80) + (description.length > 80 ? '...' : '')
      };
    } catch (error) {
      return { title: 'Error reading file', description: error.message };
    }
  }

  // Generate index content
  generateIndexContent() {
    const files = Object.keys(FILE_METADATA);

    let content = `# Memory Bank Index

## File Summary (Last Updated: ${this.currentDate})

| File | Purpose | Key Sections | Last Updated |
|------|---------|--------------|--------------|
`;

    files.forEach(file => {
      const metadata = FILE_METADATA[file];
      const filePath = path.join(MEMORY_BANK_PATH, file);
      const lastModified = this.getFileLastModified(filePath);
      const summary = this.getFileSummary(filePath);

      content += `| [${file}](${file}) | ${metadata.purpose} | ${metadata.sections} | ${lastModified} |\n`;
    });

    content += `
## Quick Access

**Start Here**: [project-brief.md](project-brief.md) → scope cốt lõi
**Current Work**: [active-context.md](active-context.md) → trạng thái hiện hành
**Architecture**: [system-patterns.md](system-patterns.md) → cấu trúc hệ thống
**Tech Stack**: [tech-context.md](tech-context.md) → công nghệ và ràng buộc

---
*Last Updated: ${this.currentDate} - Auto-generated by update-index.js*
`;

    return content;
  }

  // Update index.md
  updateIndex() {
    const indexPath = path.join(MEMORY_BANK_PATH, 'index.md');
    const newContent = this.generateIndexContent();

    try {
      fs.writeFileSync(indexPath, newContent);
      console.log(`✅ Updated index.md with ${this.currentDate} timestamp`);
      return true;
    } catch (error) {
      console.error('❌ Failed to update index.md:', error.message);
      return false;
    }
  }

  // Main execution
  run() {
    console.log('🔄 Auto-updating Memory Bank Index...');

    const success = this.updateIndex();

    if (success) {
      console.log('✅ Index update completed successfully');
    } else {
      console.log('❌ Index update failed');
      process.exit(1);
    }
  }
}

// Run if called directly
if (require.main === module) {
  const updater = new IndexUpdater();
  updater.run();
}

module.exports = IndexUpdater;
